name: drink_shop
description: "COM 4304 mini project."
publish_to: "none"
version: 1.0.1
environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.12.0
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
